/**
 * 네이밍 헬퍼 통합 re-export
 *
 * 규칙:
 * - 로직 금지, re-export만
 * - named export만 사용 (default export 금지)
 */

// ============================================
// constants.ts
// ============================================
export {
  // 제외 조건 상수
  EXCLUDED_STATE_NAMES,
  ALWAYS_EXCLUDED_NODE_TYPES,
  CONDITIONAL_NODE_TYPES,
  PLACEHOLDER_TEXT_NAMES,

  // 아이콘 라이브러리 상수
  ICON_LIBRARY_PREFIXES,
  ICON_STYLE_SUFFIXES,
  ICON_FILLER_WORDS,
  KOREAN_LABEL_MAP,
  HYPHEN_ICON_PATTERNS,
  WDS_ICON_MAP,

  // camelCase 예외 목록
  CAMEL_CASE_EXCEPTIONS,

  // 금지/일반 이름 패턴
  BLACKLIST_PATTERNS,
  GENERIC_NAMES,

  // 구조적 레이어 이름 매핑
  STRUCTURAL_LAYER_NAMES,

  // 도메인/컨텍스트 키워드
  DOMAIN_KEYWORDS,
  CONTEXT_KEYWORDS,

  // 레이아웃 프레임 상수
  LAYOUT_KEYWORD_MAP,

  // 컴포넌트 prefix 목록
  COMPONENT_PREFIXES,
} from './constants';

// ============================================
// classify.ts
// ============================================
export {
  // 제외 조건 판별
  shouldSkipNaming,

  // 최상위/스크린 판별
  isTopLevelScreenFrame,

  // 아이콘 관련 판별
  isIconLibraryName,
  isKoreanLabel,
  isHyphenIconPattern,
  isIconStateContainer,
  isInTabbarContext,

  // camelCase 판별
  isCamelCase,

  // 이름 패턴 판별
  isBlacklistedName,
  isGenericName,
  isAutoGeneratedName,

  // 레이아웃 프레임 판별
  isLayoutFrame,

  // 버튼/컴포넌트 판별
  looksLikeButton,

  // 부모-자식 관계 판별
  hasSameNameAsParent,
} from './classify';

// ============================================
// validate.ts
// ============================================
export {
  // 깊이/트리 유틸리티
  getNodeDepth,
  getRelativeDepth,

  // 조상 컴포넌트 탐색
  getAncestorComponentType,
  getAncestorComponentName,

  // 변환 조건 검증
  shouldConvertToLayout,
  shouldSkipForParentComponent,

  // 형제 충돌 검증
  hasExistingSiblingConflict,
} from './validate';

// ============================================
// normalize.ts
// ============================================
export {
  // 기본 정규화
  convertCamelCaseToPascalCase,
  cleanScreenName,
  stripParentDomainFromName,

  // 한글 변환
  convertKoreanLabel,

  // 형제 중복 해결
  resolveSiblingDuplicates,
  makeUniqueSiblingName,
} from './normalize';

// ============================================
// infer.ts
// ============================================
export {
  // 아이콘 변환
  convertHyphenIconToWDS,
  convertIconLibraryToWDS,

  // 탭 아이템 추론
  inferTabItemNameFromIcon,

  // 도메인/컨텍스트 추출
  extractParentDomainKeywords,

  // 구조적 네이밍 추론
  generateAlternativeName,
  tryStructuralNaming,
  inferSectionNameFromChildren,
  inferNameForAutoGenerated,

  // 레이아웃 추론
  inferLayoutName,
} from './infer';
