/**
 * Cleanup 모듈 인덱스
 *
 * 레이어 정리 관련 유틸리티 함수들을 export합니다.
 */

export {
  // 이름 판단
  isAutoGeneratedName,

  // 레이아웃
  resetLayoutPositioning,

  // 노드 탐색
  hasShapeDescendant,

  // 크기/비교
  isSimilarSize,
  isEmptyAutoLayoutWrapper,

  // 보호 키워드
  PROTECTED_KEYWORDS,
  hasProtectedKeyword,
} from './utils';
